apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: api-gateway
  template:
    metadata:
      labels:
        svc: api-gateway
    spec:
      containers:
        - image: vajidhussain/api-gateway
          name: api-gateway-container
          ports: 
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: NodePort
  selector:
    svc: api-gateway
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
