apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-svc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: auth-svc-postgres
  template:
    metadata:
      labels:
        svc: auth-svc-postgres
    spec:
      containers:
        - image: postgres:latest
          name: auth-svc-postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/some_name/
          volumeMounts:
            - name: auth-storagespace-cluster
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: auth-storagespace-cluster
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi    

---

apiVersion: v1
kind: Service
metadata: 
  name: postgresdb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector: 
    svc: auth-svc-postgres
    