apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-svc-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: vault-svc-mongo
  template:
    metadata:
      labels:
        svc: vault-svc-mongo
    spec:
      containers:
        - image: mongo
          name: vault-svc-mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: vault-storagespace
              mountPath: /etc/mongo
  volumeClaimTemplates:
    - metadata:
        name: vault-storagespace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi     

---

apiVersion: v1
kind: Service
metadata: 
  name: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector: 
    svc: vault-svc-mongo
    